import {
  BarChart3,
  Building2,
  ClipboardList,
  Download,
  FileDown,
  Loader2,
  ShieldCheck,
  Sparkles,
} from 'lucide-react'
import { useState } from 'react'
import CRGTab from '../components/osml/CRGTab'
import FSSTab from '../components/osml/FSSTab'
import ICRRTab from '../components/osml/ICRRTab'
import { useOsmlDownload } from '../utils/osmlDownload'

type OsmlTabId = 'icrr' | 'fss' | 'crg'

export default function OSMLAnalysisPage() {
  const [activeTab, setActiveTab] = useState<OsmlTabId>('icrr')
  const { downloading: crmDownloading, downloadFile: downloadCrmMemo } = useOsmlDownload()

  return (
    <div className="p-6">
      <header
        className="flex flex-col gap-8 rounded-[12px] border border-[#D0DCF0] bg-card-white px-8 py-6 lg:flex-row lg:items-start lg:justify-between"
        aria-label="Borrower analysis summary"
      >
        <div className="min-w-0 flex-1 space-y-3">
          <h1 className="text-[22px] font-bold leading-tight text-[#0D1B3E]">
            Outpace Spinning Mills Ltd.
          </h1>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-[14px] text-[#4A5568]">
            <span className="inline-flex items-center gap-1.5">
              <Building2 className="h-4 w-4 shrink-0" strokeWidth={2} aria-hidden />
              Outright Group
            </span>
          </div>
          <p className="text-[14px] text-[#4A5568]">
            Textile (Industry Code: 102)
          </p>
          <div className="flex flex-wrap gap-2">
            <span
              className="inline-flex items-center rounded-full bg-[#DCFCE7] px-2.5 py-0.5 text-[12px] font-semibold text-[#166534]"
              title="CIB Status"
            >
              Standard
            </span>
            <span
              className="inline-flex items-center rounded-full bg-[#FEF3C7] px-2.5 py-0.5 text-[12px] font-semibold text-[#B45309]"
              title="Audit Status"
            >
              Unaudited
            </span>
          </div>
          <p className="text-[13px] text-[#4A5568]">
            Auditor: Dewan Nazrul Islam &amp; Co.
          </p>
          <p className="text-[13px] text-[#4A5568]">
            <span className="font-medium text-[#0D1B3E]">Analysis Date:</span> 26
            December 2024{' '}
            <span className="text-[#CBD5E0]" aria-hidden>
              |
            </span>{' '}
            <span className="font-medium text-[#0D1B3E]">Financial Date:</span> 30 June
            2024
          </p>
          <p className="text-[13px] text-[#4A5568]">
            <span className="font-medium text-[#0D1B3E]">Analyst:</span> Md. Matiur
            Rahman, SRM{' '}
            <span className="text-[#CBD5E0]" aria-hidden>
              |
            </span>{' '}
            <span className="font-medium text-[#0D1B3E]">Verifier:</span> Farhana
            Afrin, SM
          </p>
        </div>

        <div className="flex shrink-0 flex-col gap-3 lg:w-[240px]">
          <button
            type="button"
            onClick={() =>
              downloadCrmMemo('OSML-CRM-Memo.xlsx', 'OSML-CRM-Memo.xlsx')
            }
            disabled={crmDownloading}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[#1A7C4A] px-4 text-sm font-semibold text-white transition-colors hover:bg-[#156542] disabled:cursor-not-allowed disabled:opacity-80"
          >
            {crmDownloading ? (
              <Loader2 className="h-4 w-4 shrink-0 animate-spin" strokeWidth={2} aria-hidden />
            ) : (
              <FileDown className="h-4 w-4 shrink-0" strokeWidth={2} aria-hidden />
            )}
            {crmDownloading ? 'Downloading...' : 'Download CRM Memo'}
          </button>
          <button
            type="button"
            className="inline-flex h-11 items-center justify-center gap-2 rounded-lg border-2 border-[#0052A5] bg-transparent px-4 text-sm font-semibold text-[#0052A5] transition-colors hover:bg-[#0052A5]/5"
          >
            <Download className="h-4 w-4 shrink-0" strokeWidth={2} aria-hidden />
            Download Full Report
          </button>
        </div>
      </header>

      <div
        className="mt-6 flex flex-col gap-4 rounded-[10px] border border-[#BFDBFE] bg-[#EFF6FF] px-6 py-4 md:flex-row md:items-center md:justify-between"
        role="status"
        aria-label="AI analysis notice"
      >
        <div className="flex min-w-0 gap-3">
          <Sparkles
            className="mt-0.5 h-5 w-5 shrink-0 text-amber-500"
            strokeWidth={2}
            aria-hidden
          />
          <div className="min-w-0">
            <p className="text-sm font-bold text-[#0D1B3E]">AI-Powered Analysis</p>
            <p className="mt-1 text-[13px] leading-relaxed text-[#4A5568]">
              This analysis was generated by the BRAC Bank Credit Engine from uploaded
              PDF financial statements. Outpace Spinning Mills Ltd. is a real borrower
              — all figures are from actual audited/unaudited statements.
            </p>
          </div>
        </div>
        <div className="flex shrink-0 flex-col items-start gap-2 md:items-end">
          <span className="text-sm font-semibold text-[#166534]">
            Processing time: 4.2 seconds
          </span>
          <span className="inline-flex rounded-full bg-[#DCFCE7] px-2.5 py-0.5 text-[12px] font-semibold text-[#166534]">
            Confidence: High
          </span>
        </div>
      </div>

      <div className="mt-8">
        <div
          className="flex gap-8 border-b border-[#E2E8F0]"
          role="tablist"
          aria-label="Regulatory outputs"
        >
          <button
            type="button"
            role="tab"
            aria-selected={activeTab === 'icrr'}
            id="osml-tab-icrr"
            aria-controls="osml-tabpanel-icrr"
            onClick={() => setActiveTab('icrr')}
            className={[
              'flex items-center gap-2 border-b-2 pb-3 text-sm transition-colors',
              activeTab === 'icrr'
                ? 'border-[#0052A5] font-bold text-[#0052A5]'
                : 'border-transparent font-medium text-[#4A5568] hover:text-[#0D1B3E]',
            ].join(' ')}
          >
            <ShieldCheck className="h-4 w-4 shrink-0" strokeWidth={2} aria-hidden />
            ICRR
          </button>
          <button
            type="button"
            role="tab"
            aria-selected={activeTab === 'fss'}
            id="osml-tab-fss"
            aria-controls="osml-tabpanel-fss"
            onClick={() => setActiveTab('fss')}
            className={[
              'flex items-center gap-2 border-b-2 pb-3 text-sm transition-colors',
              activeTab === 'fss'
                ? 'border-[#0052A5] font-bold text-[#0052A5]'
                : 'border-transparent font-medium text-[#4A5568] hover:text-[#0D1B3E]',
            ].join(' ')}
          >
            <BarChart3 className="h-4 w-4 shrink-0" strokeWidth={2} aria-hidden />
            FSS
          </button>
          <button
            type="button"
            role="tab"
            aria-selected={activeTab === 'crg'}
            id="osml-tab-crg"
            aria-controls="osml-tabpanel-crg"
            onClick={() => setActiveTab('crg')}
            className={[
              'flex items-center gap-2 border-b-2 pb-3 text-sm transition-colors',
              activeTab === 'crg'
                ? 'border-[#0052A5] font-bold text-[#0052A5]'
                : 'border-transparent font-medium text-[#4A5568] hover:text-[#0D1B3E]',
            ].join(' ')}
          >
            <ClipboardList className="h-4 w-4 shrink-0" strokeWidth={2} aria-hidden />
            CRG
          </button>
        </div>

        <div
          className="mt-6"
          role="tabpanel"
          id={
            activeTab === 'icrr'
              ? 'osml-tabpanel-icrr'
              : activeTab === 'fss'
                ? 'osml-tabpanel-fss'
                : 'osml-tabpanel-crg'
          }
          aria-labelledby={`osml-tab-${activeTab}`}
        >
          {activeTab === 'icrr' ? (
            <ICRRTab />
          ) : activeTab === 'fss' ? (
            <FSSTab />
          ) : (
            <CRGTab />
          )}
        </div>
      </div>
    </div>
  )
}
